### ISSUE TITLE
Unable to run latest Z80 Explorer on my Windows 11 laptop

### ISSUE THREAD

**Issue by prlaba** [gdevic/Z80Explorer#3]
I downloaded the latest Z80 Explorer 1.04 onto my Windows 11 laptop and ran into a security issue.

After unzipping the Z80Explorer-1.04 zip file I attempted to run Z0Explorer.exe.  Microsoft Defender complained that the app was unrecognized (unknown publisher).  When I attempted to override Defender and run it anyway, my Norton 360 Anti-virus service chimed in, said the app was unsafe (a threat called WS.Reputation.1) and quarantined it.

Has anyone else run into this?  Maybe this is a Norton thing?

Thanks,

Paul

**Comment by gdevic** [comment]
That's a false positive. I just checked the released EXE at "virustotal.com" and (of course) none of the engines flagged it.

**Comment by prlaba** [comment]
Thanks.  It appears Norton's WS.Reputation.1 virus is not a virus at all.  This link explains what's going on:

https://blog.mindworkshop.com/windows/the-norton-symantec-ws-reputation-1-false-positive/

"Norton appears to keep track of the frequency with which its users install downloadable products. As the number of users who download and install specific products increases, so too does the “reputation” of the installers in question.

When you attempt to download and install software with Norton Antivirus running, your downloaded installer will be compared against Norton’s reputation database. Installers without a sufficient “reputation” in this regard will cause Norton to display a warning – an example of which is illustrated at the beginning of this post – and remove your download before it can be installed."

I'll disable Norton and try again.

**Comment by prlaba** [comment]
Sorry for the distraction.  I ran into a similar issue back in 2022 but forgot.

The solution this time around was to simply disable Norton AV while downloading and installing/unzipping the file.  Z80 Explorer worked fine after doing that.

**Comment by prlaba** [comment]
Close this issue.
